---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ec2-user
  gather_facts: false
  tasks:
    - name: Install Httpd
      file:
        path: /home/ec2-user/myfile
        state: touch
        mode: u+rw,g-wx,o-rwx
    - name: install ntpdate
      package:
        name: ntpdate
        state: present
    - name: install ntpdate
      package:
        name: git
        state: present
