- hosts: localhost
  become: yes
 
  gather_facts: false


  tasks:
    - name: Install Httpd
      apt:
        name: apache2
        state: latest
    - name: enable httpd
      service:
        name: apache2
        enabled: yes
    - name: start the httpd
      service:
        name: apache2
        state: started
    - name: COPY STATIC WEBSITE
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0777'
    - name: check git version
      shell: git --version
    - name: check httpd status
      shell: systemctl status apache2
    - name: Create a file
      file:
        path:  /root/myfile
        state: touch
        mode: '0700'
    - name: Create a file
      file:
        path:  /root/mynewdir
        state: directory
        mode: '0700'
